# This file is generated by the tf wrapper script to configure the remote backend.
# This is used by Terraform v0.9.0+ and is NOT compatible with older versions.
# Do not edit or delete!

terraform { backend "s3" {} }
